version: "2"
services:
  api:
    image: xbrowsersync/api:custom
    restart: always
    depends_on:
      - db    
    ports:
      - 8080:8080
    environment:
      - XBROWSERSYNC_DB_USER=xbrowsersync
      - XBROWSERSYNC_DB_PWD=xbrowsersync
    volumes:
      - ./config:/usr/src/xbrowsersync-api/config
      - ./log:/var/log/xBrowserSync/
    networks:
      - backends

  db:
    image: mongo:3-stretch
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=xbrowsersync
      - MONGO_INITDB_ROOT_PASSWORD=xbrowsersync
    volumes:
      - db_data:/data/db
    networks:
      - backends

networks:
  backends:

volumes:
  db_data:
